// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCID2FurvWvVxVsRTGCHaYB6PRWd5UXIDg',
    appId: '1:493499986327:web:159acdcb3c4a3193d214d2',
    messagingSenderId: '493499986327',
    projectId: 'minute-news-3ba9d',
    authDomain: 'minute-news-3ba9d.firebaseapp.com',
    storageBucket: 'minute-news-3ba9d.appspot.com',
    measurementId: 'G-D3Z0L1X4XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU2ly3mksx7nJg70YUyWH7XuY3V9Nn7EY',
    appId: '1:493499986327:android:ade3b9cbfbabb9ccd214d2',
    messagingSenderId: '493499986327',
    projectId: 'minute-news-3ba9d',
    storageBucket: 'minute-news-3ba9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMJCNAdg2IKChIOf9dPG_zAhLEh1jwV8',
    appId: '1:493499986327:ios:49b3492cf31cfbc3d214d2',
    messagingSenderId: '493499986327',
    projectId: 'minute-news-3ba9d',
    storageBucket: 'minute-news-3ba9d.appspot.com',
    iosClientId: '493499986327-fie5ktccf37khngicpdi4pol9be7i9dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAMJCNAdg2IKChIOf9dPG_zAhLEh1jwV8',
    appId: '1:493499986327:ios:49b3492cf31cfbc3d214d2',
    messagingSenderId: '493499986327',
    projectId: 'minute-news-3ba9d',
    storageBucket: 'minute-news-3ba9d.appspot.com',
    iosClientId: '493499986327-fie5ktccf37khngicpdi4pol9be7i9dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
